# Generated by Django 4.2.11 on 2024-04-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main',
        ),
    ]
